<?php

if( ! defined('ABSPATH') ) {
	exit; // exit if accessed the file directly
}

if( function_exists('acf_add_local_field_group') ):
	$country_list_link = plugin_dir_url( __FILE__ ).'countries/names.json';

	$country_list = json_decode(file_get_contents($country_list_link),true);
	$con_list = array();
	foreach ($country_list as $key => $value) {
		$con_list[$value['alpha2Code']] = $value['name'];
	}
// MS Header Bar

acf_add_local_field_group(array(
	'key' => 'group_msheader00001',
	'title' => 'MS Header Bar',
	'fields' => array(
		array(
			'key' => 'field_mshdheadercust001',
			'label' => 'Customize Message',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_mshdheadercust002',
			'label' => 'Header Bar Title',
			'name' => 'ms_header_title',
			'type' => 'wysiwyg',
			'instructions' => 'Plese enter your Header Bar Title( optional )',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Heder Bar Title',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_mshdheaderfun001',
			'label' => 'Add Function',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' =>0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_mshdheaderfun002',
			'label' => 'Social Sharing Option',
			'name' => 'ms_header_social_sharing_option',
			'type' => 'true_false',
			'instructions' => 'Select if you want to show up social sharing buttons',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Do you want to show social sharing/following buttons?',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'Yes',
			'ui_off_text' => 'No',
		),
		array(
			'key' => 'field_mshdheaderfun003',
			'label' => 'Social Sharing Buttons',
			'name' => 'ms_header_sharing_buttons',
			'type' => 'select',
			'instructions' => 'Please choose the social sharing icons you want to use here. To select multiple values, hold ctrl and choose options',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_mshdheaderfun002',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'facebook' => 'Facebook',
				'google_p' => 'Google Plus',
				'twitter' => 'Twitter',
				'pinterest' => 'Pinterest',
				'blogger' => 'Blogger',
				'tumblr' => 'Tumblr',
				'linkedin' => 'Linkedin',
				'reddit' => 'Reddit',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 1,
			'ui' => 1,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_mshdheaderfun004',
			'label' => 'Social Sharing Button Styles',
			'name' => 'ms_header_social_sharing_button_styles',
			'type' => 'select',
			'instructions' => 'Select the button style for the social media sharing',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_mshdheaderfun002',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'square' => 'Square',
				'border_radius' => 'Radial Border',
				'circle' => 'Circle',
			),
			'default_value' => array(
				0 => 'square',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_mshdheaderfun005',
			'label' => 'Custom Border Radius',
			'name' => 'ms_header_custom_border_radius',
			'type' => 'text',
			'instructions' => 'Specify custom "top right left bottom" border radius in px or unit. i.e 10% 20% 15% 12%',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_mshdheaderfun004',
						'operator' => '==',
						'value' => 'border_radius',
					),
					array(
						'field' => 'field_mshdheaderfun002',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '5px',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_mshdheaderfun006',
			'label' => 'Button Type',
			'name' => 'ms_header_social_button_type',
			'type' => 'select',
			'instructions' => 'Please select the button type you want to use',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_mshdheaderfun002',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'share' => 'Share',
				'follow' => 'Follow',
			),
			'default_value' => array(
				0 => 'share',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_mshdheaderfun007',
			'label' => 'Pinterest pin image',
			'name' => 'ms_header_social_page_follow_pinterest_media',
			'type' => 'image',
			'instructions' => 'Please upload the image you want to pin',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_mshdheaderfun006',
						'operator' => '==',
						'value' => 'share',
					),
					array(
						'field' => 'field_mshdheaderfun003',
						'operator' => '==',
						'value' => 'pinterest',
					),
					array(
						'field' => 'field_mshdheaderfun002',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'full',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_mshdheaderfun008',
			'label' => 'Social Page URL',
			'name' => 'ms_header_social_page_url',
			'type' => 'url',
			'instructions' => 'Please insert the URL of the page that you want to share to social media.',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_mshdheaderfun002',
						'operator' => '==',
						'value' => '1',
					),
					array(
						'field' => 'field_mshdheaderfun006',
						'operator' => '==',
						'value' => 'share',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'URL to be shared to social media',
		),
		array(
			'key' => 'field_mshdheaderfun009',
			'label' => 'Follow Fb',
			'name' => 'ms_header_social_page_follow_fb',
			'type' => 'url',
			'instructions' => 'Please insert your fb page/profile url here',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_mshdheaderfun006',
						'operator' => '==',
						'value' => 'follow',
					),
					array(
						'field' => 'field_mshdheaderfun003',
						'operator' => '==',
						'value' => 'facebook',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'FB page where visitor will be redirected to.',
		),
		array(
			'key' => 'field_mshdheaderfun010',
			'label' => 'Follow Google Plus',
			'name' => 'ms_header_social_page_follow_google_plus',
			'type' => 'url',
			'instructions' => 'Please insert your Google plus page/profile url here',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_mshdheaderfun006',
						'operator' => '==',
						'value' => 'follow',
					),
					array(
						'field' => 'field_mshdheaderfun003',
						'operator' => '==',
						'value' => 'google_p',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Google Plus page where visitor will be redirected to.',
		),
		array(
			'key' => 'field_mshdheaderfun011',
			'label' => 'Follow Twitter',
			'name' => 'ms_header_social_page_follow_twitter',
			'type' => 'url',
			'instructions' => 'Please insert your Twitter profile url here',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_mshdheaderfun006',
						'operator' => '==',
						'value' => 'follow',
					),
					array(
						'field' => 'field_mshdheaderfun003',
						'operator' => '==',
						'value' => 'twitter',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Twitter profile url where visitor will be redirected to.',
		),
		array(
			'key' => 'field_mshdheaderfun012',
			'label' => 'Follow Pinterest',
			'name' => 'ms_header_social_page_follow_pinterest',
			'type' => 'url',
			'instructions' => 'Please insert your Pinterest profile url here',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_mshdheaderfun006',
						'operator' => '==',
						'value' => 'follow',
					),
					array(
						'field' => 'field_mshdheaderfun003',
						'operator' => '==',
						'value' => 'pinterest',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Pinterest profile url where visitor will be redirected to.',
		),
		array(
			'key' => 'field_mshdheaderfun013',
			'label' => 'Follow Blogger',
			'name' => 'ms_header_social_page_follow_blogger',
			'type' => 'url',
			'instructions' => 'Please insert your Blogger url here',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_mshdheaderfun006',
						'operator' => '==',
						'value' => 'follow',
					),
					array(
						'field' => 'field_mshdheaderfun003',
						'operator' => '==',
						'value' => 'blogger',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Blogger url where visitor will be redirected to.',
		),
		array(
			'key' => 'field_mshdheaderfun014',
			'label' => 'Follow Tumblr',
			'name' => 'ms_popup_social_page_follow_tumblr',
			'type' => 'url',
			'instructions' => 'Please insert your Tumblr url here',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_mshdheaderfun006',
						'operator' => '==',
						'value' => 'follow',
					),
					array(
						'field' => 'field_mshdheaderfun003',
						'operator' => '==',
						'value' => 'tumblr',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Tumblr url where visitor will be redirected to.',
		),
		array(
			'key' => 'field_mshdheaderfun015',
			'label' => 'Follow Linkedin',
			'name' => 'ms_header_social_page_follow_linkedin',
			'type' => 'url',
			'instructions' => 'Please insert your Linkedin url here',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_mshdheaderfun006',
						'operator' => '==',
						'value' => 'follow',
					),
					array(
						'field' => 'field_mshdheaderfun003',
						'operator' => '==',
						'value' => 'linkedin',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Linkedin url where visitor will be redirected to.',
		),
		array(
			'key' => 'field_mshdheaderfun016',
			'label' => 'Follow Reddit',
			'name' => 'ms_haeder_social_page_follow_reddit',
			'type' => 'url',
			'instructions' => 'Please insert your Reddit url here',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_mshdheaderfun006',
						'operator' => '==',
						'value' => 'follow',
					),
					array(
						'field' => 'field_mshdheaderfun003',
						'operator' => '==',
						'value' => 'reddit',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Reddit url where visitor will be redirected to.',
		),
		array(
			'key' => 'field_mshdheaderfun017',
			'label' => 'Use form',
			'name' => 'ms_header_use_form_or_anything_custom',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Do you want to use forms or shortcode?',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'Yes',
			'ui_off_text' => 'No',
		),
		array(
			'key' => 'field_mshdheaderfun018',
			'label' => 'Input Field Text color',
			'name' => 'ms_header_form_input_color',
			'type' => 'color_picker',
			'instructions' => 'Please choose a color for Name and Email field',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_mshdheaderfun017',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array(
			'key' => 'field_mshdheaderfun019',
			'label' => 'Input Field Background color',
			'name' => 'ms_header_form_input_back_color',
			'type' => 'color_picker',
			'instructions' => 'Please choose a background color for Name and Email field',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_mshdheaderfun017',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array(
			'key' => 'field_mshdheaderfun020',
			'label' => 'Submit Text Color',
			'name' => 'ms_header_form_submit_text_color',
			'type' => 'color_picker',
			'instructions' => 'Please choose a color for submit button text',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_mshdheaderfun017',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#ffffff',
		),
		array(
			'key' => 'field_mshdheaderfun021',
			'label' => 'Submit Background Color',
			'name' => 'ms_header_form_submit_background_color',
			'type' => 'color_picker',
			'instructions' => 'Please choose a background color for submit button text',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_mshdheaderfun017',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#ffffff',
		),
		array(
			'key' => 'field_mshdheaderfun022',
			'label' => 'Form Success Message',
			'name' => 'ms_header_form_success_message',
			'type' => 'wysiwyg',
			'instructions' => 'Insert form success message',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_mshdheaderfun017',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_mshdheaderfun023',
			'label' => 'Use Call Back Form',
			'name' => 'ms_header_use_call_back_form',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Do you want to use Call Back Action?',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'Yes',
			'ui_off_text' => 'No',
		),
		array(
			'key' => 'field_mshdheaderfun024',
			'label' => 'Input Field Text color',
			'name' => 'ms_header_callback_input_color',
			'type' => 'color_picker',
			'instructions' => 'Please choose a colour for input fields',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_mshdheaderfun023',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array(
			'key' => 'field_mshdheaderfun025',
			'label' => 'Input Field Background color',
			'name' => 'ms_header_callback_input_background_color',
			'type' => 'color_picker',
			'instructions' => 'Please choose a background color input fields',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_mshdheaderfun023',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),

		array(
			'key' => 'field_mshdheaderfun026',
			'label' => 'Submit Text Color',
			'name' => 'ms_header_callback_submit_text_color',
			'type' => 'color_picker',
			'instructions' => 'Please choose a color for submit button text',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_mshdheaderfun023',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#ffffff',
		),

		array(
			'key' => 'field_mshdheaderfun027',
			'label' => 'Submit Background Color',
			'name' => 'ms_header_callback_submit_background_color',
			'type' => 'color_picker',
			'instructions' => 'Please choose a background color for submit button text',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_mshdheaderfun023',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#ffffff',
		),
		array(
			'key' => 'field_mshdheaderfun028',
			'label' => 'Callback Success Message',
			'name' => 'ms_header_callback_success',
			'type' => 'wysiwyg',
			'instructions' => 'Insert Callback success message',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_mshdheaderfun023',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),

		array(
			'key' => 'field_mshdheaderfun050',
			'label' => 'Enable Coupon Code?',
			'name' => 'ms_header_enable_coupon_code',
			'type' => 'true_false',
			'instructions' => 'Do you want to enable coupon code',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'Yes',
			'ui_off_text' => 'No',
		),
		array(
			'key' => 'field_mshdheaderfun051',
			'label' => 'The Coupon Code',
			'name' => 'ms_header_the_coupon_code',
			'type' => 'text',
			'instructions' => 'Please insert the coupon code',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_mshdheaderfun050',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '80OFF',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		
		array(
			'key' => 'field_mshdheaderfun031',
			'label' => 'Button redirect',
			'name' => 'ms_haeder_button_redirect_url',
			'type' => 'url',
			'instructions' => 'URL to redirect',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_mshdheaderfun017',
						'operator' => '!=',
						'value' => '1',
					),
					array(
						'field' => 'field_mshdheaderfun023',
						'operator' => '!=',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#',
			'placeholder' => '',
		),
		array(
			'key' => 'field_mshdheaderfun032',
			'label' => 'Button Text',
			'name' => 'ms_header_button_text',
			'type' => 'text',
			'instructions' => 'Button text',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_mshdheaderfun017',
						'operator' => '!=',
						'value' => '1',
					),
					array(
						'field' => 'field_mshdheaderfun023',
						'operator' => '!=',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Click Here',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_mshdheaderfun0321',
			'label' => 'Button Text Colour',
			'name' => 'ms_header_btn_text_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_mshdheaderfun017',
						'operator' => '!=',
						'value' => '1',
					),
					array(
						'field' => 'field_mshdheaderfun023',
						'operator' => '!=',
						'value' => '1',
					),
				),
			),
			'default_value' => '#ffffff',
		),
		array(
			'key' => 'field_mshdheaderfun0322',
			'label' => 'Button Background Colour',
			'name' => 'ms_header_btn_back_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_mshdheaderfun017',
						'operator' => '!=',
						'value' => '1',
					),
					array(
						'field' => 'field_mshdheaderfun023',
						'operator' => '!=',
						'value' => '1',
					),
				),
			),
			'default_value' => '#ff0000',
		),
		array(
			'key' => 'field_mshdheaderfun034',
			'label' => 'Countdown Timer Options',
			'name' => 'ms_header_countdown_timer_options',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Do you want to use countdown timer?',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'Yes',
			'ui_off_text' => 'No',
		),
		array(
			'key' => 'field_mshdheaderfun035',
			'label' => 'Expire Year',
			'name' => 'ms_header_countdown_expire_year',
			'type' => 'number',
			'instructions' => 'Please insert the year to countdown.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_mshdheaderfun034',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => 2018,
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_mshdheaderfun036',
			'label' => 'Expire Month',
			'name' => 'ms_header_countdown_expire_month',
			'type' => 'number',
			'instructions' => 'Please insert the month of the year to countdown.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_mshdheaderfun034',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '01',
			'max' => 12,
			'step' => '',
		),
		array(
			'key' => 'field_mshdheaderfun037',
			'label' => 'Expire Day',
			'name' => 'ms_header_countdown_expire_days',
			'type' => 'number',
			'instructions' => 'Please insert the day of the month to countdown.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_mshdheaderfun034',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '01',
			'max' => 31,
			'step' => 0,
		),
		array(
			'key' => 'field_mshdheaderfun038',
			'label' => 'Expire Hours',
			'name' => 'ms_header_countdown_expire_hours',
			'type' => 'number',
			'instructions' => 'Please insert the hour of the day to countdown.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_mshdheaderfun034',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '01',
			'max' => 24,
			'step' => '',
		),
		array(
			'key' => 'field_mshdheaderfun039',
			'label' => 'Expire Minutes',
			'name' => 'ms_header_countdown_expire_min',
			'type' => 'number',
			'instructions' => 'Please insert the minutes of the hour to countdown.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_mshdheaderfun034',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '01',
			'max' => 60,
			'step' => '',
		),
		array(
			'key' => 'field_mshdheaderfun040',
			'label' => 'Expire Seconds',
			'name' => 'ms_header_countdown_expire_sec',
			'type' => 'number',
			'instructions' => 'Please insert the seconds of the minute to countdown.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_mshdheaderfun034',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '01',
			'max' => 60,
			'step' => '',
		),
		array(
			'key' => 'field_mshdheaderfun041',
			'label' => 'Clock Head color',
			'name' => 'ms_header_clock_head_color',
			'type' => 'color_picker',
			'instructions' => 'Please choose a color for Clock head/clock texts',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_mshdheaderfun034',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#ffffff',
		),
		array(
			'key' => 'field_mshdheaderdisrule001',
			'label' => 'Design Rules',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_mshdheaderdisrule002',
			'label' => 'Header Position',
			'name' => 'ms_header_position',
			'type' => 'select',
			'instructions' => 'Select Header Bar position',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'top' => 'Top',
				'bottom' => 'Bottom',
			),
			'default_value' => array(
				0 => 'top',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_mshdheaderdisrule003',
			'label' => 'Background Color',
			'name' => 'ms_header_background_color',
			'type' => 'color_picker',
			'instructions' => 'Choose a background color for Header Bar',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array(
			'key' => 'field_mshdheaderdisrule004',
			'label' => 'Background Image',
			'name' => 'ms_header_background_image',
			'type' => 'image',
			'instructions' => 'Upload an image to use as background',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'full',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		), 
		array(
			'key' => 'field_mshdheaderdisrule005',
			'label' => 'Border Size',
			'name' => 'ms_header_border_size',
			'type' => 'text',
			'instructions' => 'Specify border in px as follows top right bottom left. i.e. 2px 3px 1px 0px',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 0,
			'placeholder' => 'Specify border size',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_mshdheaderdisrule006',
			'label' => 'Border Style',
			'name' => 'ms_popup_border_style',
			'type' => 'select',
			'instructions' => 'Please select the border style you want',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'none' => 'none',
				'hidden' => 'hidden',
				'dotted' => 'dotted',
				'dashed' => 'dashed',
				'solid' => 'solid',
				'double' => 'double',
				'groove' => 'groove',
				'ridge' => 'ridge',
				'inset' => 'inset',
				'outset' => 'outset',
				'initial' => 'initial',
				'inherit' => 'inherit',
			),
			'default_value' => array(
				0 => 'none',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_mshdheaderdisrule007',
			'label' => 'Border Color',
			'name' => 'ms_popup_border_color',
			'type' => 'color_picker',
			'instructions' => 'Choose a border color for the popup',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array(
			'key' => 'field_mshdheaderdisrule008',
			'label' => 'Padding',
			'name' => 'ms_header_padding',
			'type' => 'text',
			'instructions' => 'Specify padding in px as follows top right bottom left. i.e. 2px 3px 1px 0px',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 0,
			'placeholder' => 'Specify padding',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		/*array(
			'key' => 'field_mshdheaderdisrule009',
			'label' => 'Header Animation',
			'name' => 'ms_popup_animation',
			'type' => 'select',
			'instructions' => 'Please choose an animation to animate the popup',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'bounce' => 'bounce',
				'flash' => 'flash',
				'pulse' => 'pulse',
				'rubberBand' => 'rubberBand',
				'shake' => 'shake',
				'headShake' => 'headShake',
				'swing' => 'swing',
				'tada' => 'tada',
				'wobble' => 'wobble',
				'jello' => 'jello',
				'bounceIn' => 'bounceIn',
				'bounceInDown' => 'bounceInDown',
				'bounceInLeft' => 'bounceInLeft',
				'bounceInRight' => 'bounceInRight',
				'bounceInUp' => 'bounceInUp',
				'bounceOut' => 'bounceOut',
				'bounceOutDown' => 'bounceOutDown',
				'bounceOutLeft' => 'bounceOutLeft',
				'bounceOutRight' => 'bounceOutRight',
				'bounceOutUp' => 'bounceOutUp',
				'fadeIn' => 'fadeIn',
				'fadeInDown' => 'fadeInDown',
				'fadeInDownBig' => 'fadeInDownBig',
				'fadeInLeft' => 'fadeInLeft',
				'fadeInLeftBig' => 'fadeInLeftBig',
				'fadeInRight' => 'fadeInRight',
				'fadeInRightBig' => 'fadeInRightBig',
				'fadeInUp' => 'fadeInUp',
				'fadeInUpBig' => 'fadeInUpBig',
				'fadeOut' => 'fadeOut',
				'fadeOutDown' => 'fadeOutDown',
				'fadeOutDownBig' => 'fadeOutDownBig',
				'fadeOutLeft' => 'fadeOutLeft',
				'fadeOutLeftBig' => 'fadeOutLeftBig',
				'fadeOutRight' => 'fadeOutRight',
				'fadeOutRightBig' => 'fadeOutRightBig',
				'fadeOutUp' => 'fadeOutUp',
				'fadeOutUpBig' => 'fadeOutUpBig',
				'flip' => 'flip',
				'flipInX' => 'flipInX',
				'flipInY' => 'flipInY',
				'flipOutX' => 'flipOutX',
				'flipOutY' => 'flipOutY',
				'lightSpeedIn' => 'lightSpeedIn',
				'lightSpeedOut' => 'lightSpeedOut',
				'rotateIn' => 'rotateIn',
				'rotateInDownLeft' => 'rotateInDownLeft',
				'rotateInDownRight' => 'rotateInDownRight',
				'rotateInUpLeft' => 'rotateInUpLeft',
				'rotateInUpRight' => 'rotateInUpRight',
				'rotateOut' => 'rotateOut',
				'rotateOutDownLeft' => 'rotateOutDownLeft',
				'rotateOutDownRight' => 'rotateOutDownRight',
				'rotateOutUpLeft' => 'rotateOutUpLeft',
				'rotateOutUpRight' => 'rotateOutUpRight',
				'hinge' => 'hinge',
				'jackInTheBox' => 'jackInTheBox',
				'rollIn' => 'rollIn',
				'rollOut' => 'rollOut',
				'zoomIn' => 'zoomIn',
				'zoomInDown' => 'zoomInDown',
				'zoomInLeft' => 'zoomInLeft',
				'zoomInRight' => 'zoomInRight',
				'zoomInUp' => 'zoomInUp',
				'zoomOut' => 'zoomOut',
				'zoomOutDown' => 'zoomOutDown',
				'zoomOutLeft' => 'zoomOutLeft',
				'zoomOutRight' => 'zoomOutRight',
				'zoomOutUp' => 'zoomOutUp',
				'slideInDown' => 'slideInDown',
				'slideInLeft' => 'slideInLeft',
				'slideInRight' => 'slideInRight',
				'slideInUp' => 'slideInUp',
				'slideOutDown' => 'slideOutDown',
				'slideOutLeft' => 'slideOutLeft',
				'slideOutRight' => 'slideOutRight',
				'slideOutUp' => 'slideOutUp',
			),
			'default_value' => array(
				0 => 'swing',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		), */
		array(
			'key' => 'field_mshdheaderdisset001',
			'label' => 'Display Setting',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_mshdheaderdisset002',
			'label' => 'Use Target Countries',
			'name' => 'ms_header_use_target_countries',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'Yes',
			'ui_off_text' => 'No',
		),
		array(
			'key' => 'field_mshdheaderdisset003',
			'label' => 'Choose Target Countries',
			'name' => 'ms_header_target_countries',
			'type' => 'select',
			'instructions' => 'Please select the countries you want to show this popup',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_mshdheaderdisset002',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => $con_list,
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 1,
			'ui' => 1,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_mshdheaderdisset004',
			'label' => 'Devices where you to show this popup',
			'name' => 'ms_header_screen_size_to_display',
			'type' => 'select',
			'instructions' => 'Please select the smallest device to support this popup.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				220 => 'Smartphone',
				320 => 'Tablet',
				768 => 'Desktop',
				'all' => 'All'
			),
			'default_value' => array(
				'all' => 'All'
			),
			'allow_null' => 0,
			'multiple' => 1,
			'ui' => 1,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_mshdheaderdisset005',
			'label' => 'Delay to Popup',
			'name' => 'ms_header_delay_to_show',
			'type' => 'select',
			'instructions' => 'Select milli seconds to delay the popup after page loads.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				0 => '0',
				5000 => '5000',
				10000 => '10000',
				15000 => '15000',
				20000 => '20000',
				25000 => '25000',
				30000 => '30000',
				35000 => '35000',
				40000 => '40000',
				45000 => '45000',
				50000 => '50000',
			),
			'default_value' => array(
				0 => 5000,
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_mshdheadersub001',
			'label' => 'Submissions',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_mshdheadersub002',
			'label' => 'Choose a Submission',
			'name' => 'ms_header_submission_want_to_show',
			'type' => 'button_group',
			'instructions' => 'Choose a action to see the Submission Report',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'form_submission' => 'Form Data',
				'callback_submission' => 'Callback Data',
			),
			'allow_null' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_mshdheadersub003',
			'label' => 'Form Data',
			'name' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
					array(
							array(
								'field' => 'field_mshdheadersub002',
								'operator' => '==',
								'value' => 'form_submission',
							),
						),
					),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'sub_fields' => array(
				array(
					'key' => 'field_mshdheadersub004',
					'label' => '',
					'name' => '',
					'type' => 'hidden',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'min' => '',
					'max' => '',
					'step' => '',
					'prepend' => '',
					'append' => '',
				),
			),
		),
		array(
			'key' => 'field_mshdheadersub005',
			'label' => 'Callback',
			'name' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
					array(
							array(
								'field' => 'field_mshdheadersub002',
								'operator' => '==',
								'value' => 'callback_submission',
							),
						),
					),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'sub_fields' => array(
				array(
					'key' => 'field_mshdheadersub006',
					'label' => '',
					'name' => '',
					'type' => 'hidden',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'min' => '',
					'max' => '',
					'step' => '',
					'prepend' => '',
					'append' => '',
				),
			),
		
		),

	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'msh-header-bar',
			),
			array(
				'param' => 'post_type',
				'operator' => '!=',
				'value' => 'ms-simple-popup',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'custom_fields',
		4 => 'discussion',
		5 => 'comments',
		6 => 'revisions',
		7 => 'slug',
		8 => 'author',
		9 => 'format',
		10 => 'page_attributes',
		11 => 'featured_image',
		12 => 'categories',
		13 => 'tags',
		14 => 'send-trackbacks',
	),
	'active' => 1,
	'description' => '',
));


acf_add_local_field_group(array(
	'key' => 'group_msheader5a79e5232e1b6',
	'title' => 'MS Header Bar',
	'fields' => array(

		array(
			'key' => 'field_mshdheaderpage0001',
			'label' => 'Select Header',
			'name' => 'msh_header_select_to_use',
			'type' => 'post_object',
			'instructions' => 'Please select the Header you want to use in this post/page.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'msh-header-bar',
			),
			'taxonomy' => array(
			),
			'allow_null' => 1,
			'multiple' => 1,
			'return_format' => 'id',
			'ui' => 1,
		),

		
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '!=',
				'value' => 'ms-simple-popup',
			),
			array(
				'param' => 'post_type',
				'operator' => '!=',
				'value' => 'ms-simple-slider',
			),
			array(
				'param' => 'post_type',
				'operator' => '!=',
				'value' => 'ms-boost-sales'
			),
			array(
				'param' => 'post_type',
				'operator' => '!=',
				'value' => 'msh-header-bar'
			),
			array(
				'param' => 'post_type',
				'operator' => '!=',
				'value' => 'ms-header-bar'
			)
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;